arb-dir: lib/l10n
output-dir: lib/l10n
template-arb-file: phrases_en.arb
output-localization-file: phrases.dart
output-class: Phrases
use-deferred-loading: true
gen-inputs-and-outputs-list: lib/l10n
synthetic-package: false
required-resource-attributes: false
format: true
suppress-warnings: false