arb-dir: lib/src/l10n
output-dir: lib/src/l10n
template-arb-file: app_en.arb
use-deferred-loading: true
gen-inputs-and-outputs-list: lib/src/l10n
synthetic-package: false
required-resource-attributes: false
format: true
suppress-warnings: false