arb-dir: lib/l10n
output-dir: lib/l10n
template-arb-file: app_en.arb
use-deferred-loading: true
gen-inputs-and-outputs-list: lib/l10n
synthetic-package: false
required-resource-attributes: false
nullable-getter: false
format: true
suppress-warnings: false