library empathetech_flutter_ui;

import 'package:empathetech_flutter_ui/empathetech_flutter_ui.dart';

import 'package:flutter/material.dart';
import 'package:flutter_platform_widgets/flutter_platform_widgets.dart';

class EzMaterialAppData extends MaterialAppData {
  /// [MaterialAppData] wrapper that uses handles switching between
  /// [ezThemeData] light && dark
  EzMaterialAppData({
    Key? widgetKey,
    GlobalKey<NavigatorState>? navigatorKey,
    Widget? home,
    Map<String, Widget Function(BuildContext)>? routes,
    String? initialRoute,
    Route<dynamic>? Function(RouteSettings)? onGenerateRoute,
    Route<dynamic>? Function(RouteSettings)? onUnknownRoute,
    List<NavigatorObserver>? navigatorObservers,
    String? title,
    String Function(BuildContext)? onGenerateTitle,
    Color? color,
    Locale? locale,
    Iterable<LocalizationsDelegate<dynamic>>? localizationsDelegates,
    Locale? Function(List<Locale>?, Iterable<Locale>)?
        localeListResolutionCallback,
    Locale? Function(Locale?, Iterable<Locale>)? localeResolutionCallback,
    Iterable<Locale>? supportedLocales,
    bool? showPerformanceOverlay,
    bool? checkerboardRasterCacheImages,
    bool? checkerboardOffscreenLayers,
    bool? showSemanticsDebugger,
    bool? debugShowCheckedModeBanner,
    Map<LogicalKeySet, Intent>? shortcuts,
    Map<Type, Action<Intent>>? actions,
    List<Route<dynamic>> Function(String)? onGenerateInitialRoutes,
    String? restorationScopeId,
    ScrollBehavior? scrollBehavior,
    bool? useInheritedMediaQuery,
    ThemeData? theme,
    bool? debugShowMaterialGrid,
    ThemeData? darkTheme,
    ThemeMode? themeMode,
    GlobalKey<ScaffoldMessengerState>? scaffoldMessengerKey,
    Curve themeAnimationCurve = Curves.linear,
    Duration themeAnimationDuration = kThemeAnimationDuration,
  }) : super(
          widgetKey: widgetKey,
          navigatorKey: navigatorKey,
          home: home,
          routes: routes,
          initialRoute: initialRoute,
          onGenerateRoute: onGenerateRoute,
          onUnknownRoute: onUnknownRoute,
          navigatorObservers: navigatorObservers,
          title: title,
          onGenerateTitle: onGenerateTitle,
          color: color,
          locale: locale,
          localizationsDelegates: localizationsDelegates,
          localeListResolutionCallback: localeListResolutionCallback,
          localeResolutionCallback: localeResolutionCallback,
          supportedLocales: supportedLocales,
          showPerformanceOverlay: showPerformanceOverlay,
          checkerboardRasterCacheImages: checkerboardRasterCacheImages,
          checkerboardOffscreenLayers: checkerboardOffscreenLayers,
          showSemanticsDebugger: showSemanticsDebugger,
          debugShowCheckedModeBanner: debugShowCheckedModeBanner,
          shortcuts: shortcuts,
          actions: actions,
          onGenerateInitialRoutes: onGenerateInitialRoutes,
          restorationScopeId: restorationScopeId,
          scrollBehavior: scrollBehavior,
          useInheritedMediaQuery: useInheritedMediaQuery,
          theme: theme ?? ezThemeData(light: true),
          debugShowMaterialGrid: debugShowMaterialGrid,
          darkTheme: darkTheme ?? ezThemeData(light: false),
          themeMode: themeMode ?? ThemeMode.system,
          scaffoldMessengerKey: scaffoldMessengerKey,
          themeAnimationCurve: themeAnimationCurve,
          themeAnimationDuration: themeAnimationDuration,
        );
}
